name: Release SDK

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para tags
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Calcular nova versão
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          CURRENT_VERSION=${LAST_TAG#v}

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Nova versão: $NEW_VERSION"

      - name: Atualizar versão no gradle.properties
        run: |
          if grep -q "VERSION_NAME" gradle.properties; then
            sed -i "s/VERSION_NAME=.*/VERSION_NAME=${{ steps.version.outputs.new_version }}/" gradle.properties
          else
            echo "VERSION_NAME=${{ steps.version.outputs.new_version }}" >> gradle.properties
          fi

      - name: Build SDK
        run: ./gradlew clean assembleRelease

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: "Release v${{ steps.version.outputs.new_version }}"
          body: |
            🚀 Nova versão do SDK publicada automaticamente!
            • Versão: **${{ steps.version.outputs.new_version }}**
            • Gerada automaticamente a partir do PR #${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar no GitHub Packages
        run: ./gradlew publish
        env:
          VERSION_NAME: ${{ steps.version.outputs.new_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
